apiVersion: v1
kind: PersistentVolume
metadata:
  name: task5-pv-volume001
  namespace: storage-ns
  labels:
    type: local
spec:
  storageClassName: manual
  capacity: 
    storage: 10Gi
  accessModes: 
    - ReadWriteOnce
  hostPath: 
    path: /mnt/data
    
