apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task5-pvc-volume001
  namespace: storage-ns
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi


