apiVersion: v1
kind: LimitRange
metadata:
  name: rm-for-namespace
spec:
  limits:
  - min:
      memory: 20Mi
      cpu: "0.20m"
    max:
      memory: 300Mi
      cpu: "1" 

    default:
      memory: 50Mi
      cpu: "0.5m"

    defaultRequest:
      memory: 25Mi
      cpu: "0.25m"
    type: Container
kind: ResourceQuota
metadata:
  name: resource-quota001
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 1Gi
    limits.cpu: "4"
    limits.memory: 2Gi
    pods: "3"




